'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Toaster} from 'sonner';
import type {Attempt} from '@/lib/retry/types';
import {Header,Footer,Metric,AttemptDetails,api,number,duration,money} from '../retry-shared';
export default function Cemetery(){
 const [items,setItems]=useState<Attempt[]>([]),[total,setTotal]=useState(0),[current,setCurrent]=useState<Attempt|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[details,setDetails]=useState<Attempt|null>(null),[busy,setBusy]=useState(false);
 const countRef=useRef(0);countRef.current=items.length;
 const refresh=useCallback(async()=>{try{const data=await api('cemetery');setItems(previous=>{const merged=new Map(previous.map(a=>[a.id,a]));for(const a of data.items)merged.set(a.id,a);return Array.from(merged.values()).sort((a,b)=>b.attempt_number-a.attempt_number)});setTotal(data.total);setCurrent(data.current);setLoaded(true);setError('');return data}catch(e){setError((e as Error).message);return null}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer)},[refresh]);
 const loadMore=async()=>{setBusy(true);try{const data=await api('cemetery?offset='+countRef.current);setItems(previous=>{const merged=new Map(previous.map(a=>[a.id,a]));for(const a of data.items)merged.set(a.id,a);return Array.from(merged.values()).sort((a,b)=>b.attempt_number-a.attempt_number)});setTotal(data.total);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_retry_cemetery',description:'Read the newest dead RE:TRY attempts, final statistics and the total number of fallen attempts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const data=await refresh();if(!data)throw new Error('Cemetery unavailable');return data}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[refresh]);
 return <div className="wrap cemetery"><Toaster theme="dark"/><Header cemetery error={!!error}/><section className="intro"><div><p className="eyebrow">RE:TRY / ARCHIVE OF THE FALLEN</p><h1>The Cemetery<span>.</span></h1><p className="description" style={{marginTop:18,fontSize:16}}>Every attempt eventually leaves a trace.</p></div><div className="intro-note">The tokens rest here.<br/>The experiment lives on.</div></section><div className="cemetery-counts"><Metric label="DEAD ATTEMPTS" value={loaded?number(total):'—'}/><Metric label="CURRENT ATTEMPT" value={loaded?(current?'#'+number(current.attempt_number):'NONE'):'—'}/></div>
 {error&&<div className="notice" role="alert">{error} <button className="view" onClick={()=>void refresh()}>RECONNECT</button></div>}
 {!loaded?<div className="loading">OPENING THE ARCHIVE...</div>:items.length?<><section className="cemetery-grid" aria-label="Dead attempts">{items.map(a=><button key={a.id} className="grave mono" onClick={()=>setDetails(a)} aria-label={`Open RE:TRY ${number(a.attempt_number)} final statistics`}><img className="token-logo" src={a.logo_url} alt={`${a.token_symbol} logo`}/><span className="rip">R.I.P.</span><h2>RE:TRY #{number(a.attempt_number)}</h2><span className="symbol">${a.token_symbol}</span><span className="lifespan">{duration(a.lifespan??Math.max(0,(a.ended_at??a.created_at)-a.created_at)).toUpperCase()}</span><span className="date">Dead: {a.ended_at?new Date(a.ended_at).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—'}</span><span className="grave-summary">PEAK {money(a.peak_market_cap)}</span></button>)}</section>{items.length<total&&<button className="view load-more" disabled={busy} onClick={()=>void loadMore()}>{busy?'LOADING...':'LOAD MORE ATTEMPTS'}</button>}</>:<div className="cemetery-empty"><p className="mono">NO ATTEMPTS HAVE FALLEN.</p><p className="description">The first trace will appear when the administrator closes an attempt.</p></div>}
 <div className="cemetery-floor"/><p className="eyebrow" style={{textAlign:'center',marginBottom:0}}>THE ATTEMPT ENDS. RE:TRY REMAINS.</p><AttemptDetails attempt={details} onClose={()=>setDetails(null)}/><Footer/></div>
}
