import {database} from './db';
import {ATTEMPT_CONFIG as C} from './config';
export type Session={id:string;wallet_address:string|null;challenge:string;created_at:number;last_action_at:number;last_simulation_at:number};
export function enforceOrigin(request:Request){const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)throw new Error('Origin rejected')}
export async function rateLimit(request:Request){const db=database(),now=Date.now(),ip=request.headers.get('cf-connecting-ip')??'local';
 const key=`${ip}:${Math.floor(now/60000)}`;const row=await db.prepare('INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+120000).first<{count:number}>();
 await db.prepare('DELETE FROM rate_limits WHERE expires_at<?').bind(now).run();if((row?.count??0)>C.ipRequestsPerMinute)throw new Error('Too many requests. Try again in a minute.');
}
export async function session(request:Request){const id=request.headers.get('cookie')?.match(/(?:^|;\s*)retry_session=([a-f0-9-]{36})/)?.[1];if(!id)return null;return database().prepare('SELECT * FROM sessions WHERE id=? AND created_at>?').bind(id,Date.now()-C.sessionLifetimeMs).first<Session>()}
export async function createSession(request:Request){const existing=await session(request);if(existing&&(existing.wallet_address||Date.now()-existing.created_at<C.challengeLifetimeMs))return existing;const now=Date.now(),id=crypto.randomUUID(),challenge=`RE:TRY\nSign in to the simulated community vote.\nNo transactions or token permissions.\nOrigin: ${new URL(request.url).origin}\nNonce: ${crypto.randomUUID()}\nIssued: ${new Date(now).toISOString()}`;
 await database().prepare('INSERT INTO sessions (id,challenge,created_at,last_action_at,last_simulation_at) VALUES (?,?,?,0,0)').bind(id,challenge,now).run();return {id,challenge,created_at:now,wallet_address:null,last_action_at:0,last_simulation_at:0};
}
export function cookie(request:Request,id:string){return `retry_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=86400${new URL(request.url).protocol==='https:'?'; Secure':''}`}
function base58(s:string){const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=BigInt(0);for(const c of s){const d=alphabet.indexOf(c);if(d<0)throw new Error('Invalid wallet');n=n*BigInt(58)+BigInt(d)}const bytes=[];while(n){bytes.unshift(Number(n%BigInt(256)));n/=BigInt(256)}for(const c of s){if(c!=='1')break;bytes.unshift(0)}return new Uint8Array(bytes)}
export async function verifyWallet(s:Session,wallet:string,signature:number[]){if(Date.now()-s.created_at>C.challengeLifetimeMs)throw new Error('Challenge expired. Reload and reconnect.');const bytes=base58(wallet);if(bytes.length!==32||signature.length!==64||!signature.every(v=>Number.isInteger(v)&&v>=0&&v<=255))throw new Error('Invalid signature');const key=await crypto.subtle.importKey('raw',bytes,'Ed25519',false,['verify']);if(!await crypto.subtle.verify('Ed25519',key,new Uint8Array(signature),new TextEncoder().encode(s.challenge)))throw new Error('Wallet signature rejected')}
export function errorResponse(e:unknown){const message=e instanceof Error?e.message:'Service unavailable';const status=message.includes('Too many')?429:message.includes('storage')?503:400;console.error('RE:TRY request error',message);return Response.json({error:message},{status,headers:{'Cache-Control':'no-store'}})}

