'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Copy,Check} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import type {Attempt,Snapshot} from '@/lib/retry/types';
import {api,Header,Footer,Metric,AttemptDetails,money,num,number,clock,duration} from './retry-shared';
import AdminControls from './retry-admin';
export default function Dashboard(){
 const [state,setState]=useState<Snapshot|null>(null),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[error,setError]=useState(''),[details,setDetails]=useState<Attempt|null>(null),[copied,setCopied]=useState(false);
 const stateRef=useRef(state);stateRef.current=state;
 const refresh=useCallback(async()=>{try{const data=await api('state');stateRef.current=data;setState(data);setOffset(data.serverTime-Date.now());setError('');return data}catch(e){setError((e as Error).message);return null}},[]);
 useEffect(()=>{void refresh();const poll=setInterval(()=>void refresh(),5000),timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(timer)}},[refresh]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_retry_state',description:'Read the current simulated RE:TRY attempt, statistics and previous attempts.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const data=await refresh();if(!data)throw new Error('Attempt data unavailable');return {attempt:data.attempt,metrics:data.metrics,deadCount:data.deadCount}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[refresh]);
 const copy=async()=>{if(!state?.attempt)return;try{await navigator.clipboard.writeText(state.attempt.token_address);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{toast.error('Clipboard unavailable. Select and copy the mint text.')}};
 const time=now+offset,a=state?.attempt,m=state?.metrics,points=state?.chart.map(p=>p.join(',')).join(' ')??'';
 return <div className="wrap"><Toaster theme="dark" position="bottom-right"/><Header error={!!error}/><section className="intro"><div><p className="eyebrow">ONE EXPERIMENT. INFINITE ATTEMPTS.</p><h1>Every attempt can fail.<br/>The project <span>continues.</span></h1></div><div className="intro-note">Every failure becomes history.<br/>The next attempt begins.</div></section>
 {error&&<div className="notice" role="alert">{error} {state?'Showing the last received statistics.':''} <button className="view" onClick={()=>void refresh()}>RECONNECT</button></div>}
 {!state?<div className="panel loading">CONNECTING TO RE:TRY...</div>:<>
 <section className="panel" aria-label="Current attempt"><div className="panel-top"><span>CURRENT ATTEMPT</span><span>{a?'SOLANA / SIMULATED':'AWAITING NEXT ATTEMPT'}</span></div>{a&&m?<><div className="attempt-grid"><div className="identity"><span className="status mono"><span className="dot"/>RUNNING</span><div className="attempt-number mono"><small>#</small>{number(a.attempt_number)}</div><div className="token-line mono"><img src={a.logo_url} alt={`${a.token_symbol} logo`}/><span>${a.token_symbol}</span></div><div className="mint mono"><span>MINT</span><span className="mint-value" title={a.token_address}>{a.token_address}</span><button className="icon-button" onClick={()=>void copy()} aria-label="Copy mint address">{copied?<Check size={14}/>:<Copy size={14}/>}</button></div></div><div className="data-side"><div className="metrics"><Metric label="MARKET CAP" value={money(m.marketCap)}/><Metric label="LIQUIDITY" value={money(m.liquidity)}/><Metric label="HOLDERS" value={num(m.holders)}/></div><div className="chart-header mono"><span>MARKET CAP / CURRENT ATTEMPT</span><span>1M INTERVAL</span></div><svg className="chart" viewBox="0 0 600 120" preserveAspectRatio="none" role="img" aria-label="Simulated market capitalization over time">{[30,65,100].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="#2b3a23" strokeDasharray="3 5"/>)}<polyline points={points} fill="none" stroke="#c1f879" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/>{state.chart.length>0&&<circle cx={state.chart[state.chart.length-1][0]} cy={state.chart[state.chart.length-1][1]} r="3" fill="#c1f879"/>}</svg><div className="chart-labels mono"><span>{duration(Math.min(m.ageMs,49*60000))} AGO</span><span>NOW</span></div></div></div><div className="activity-grid"><Metric label="TOTAL VOLUME" value={money(m.totalVolume)}/><Metric label="BUYS" value={num(m.buys)}/><Metric label="SELLS" value={num(m.sells)}/><Metric label="TRANSACTIONS" value={num(m.transactions)}/></div><div className="activity-strip mono"><span className="activity-name">ACTIVITY</span><Progress value={m.activity} aria-label="Simulated token activity" className="progress-meter rounded-none bg-[#2b3a20] [&_[data-slot=progress-indicator]]:bg-[#c1f879]"/><span className="activity-value">{m.activity}%</span><span className="age">AGE {clock(time-a.created_at)}</span></div></>:<div className="empty-panel"><span className="empty-mark mono">#___</span><h2>The last attempt left a trace.</h2><p className="description">There is no active attempt.<br/>The next one begins when the administrator registers it.</p><a className="text-link mono" href="/cemetery">ENTER THE CEMETERY</a></div>}</section>
 <AdminControls state={state} refresh={refresh}/>
 <section className="previous"><div className="section-header"><h2>Previous attempts</h2><a className="text-link mono" href="/cemetery">ENTER THE CEMETERY</a></div>{state.previous.length?<div className="previous-grid">{state.previous.slice(0,3).map(a=><button className="previous-card" key={a.id} onClick={()=>setDetails(a)} aria-label={`View RE:TRY ${number(a.attempt_number)}`}><img src={a.logo_url} alt=""/><div><strong>#{number(a.attempt_number)}</strong><small>{duration(a.lifespan??0)}</small></div><span className="dead-label">DEAD</span></button>)}</div>:<p className="description">No attempts have been buried yet.</p>}</section>
 </>}
 <AttemptDetails attempt={details} onClose={()=>setDetails(null)}/><Footer/></div>
}
