'use client';
import Link from 'next/link';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Attempt} from '@/lib/retry/types';
export const money=(n:number|null)=>n===null?'—':'$'+Math.round(n).toLocaleString('en-US');
export const num=(n:number|null)=>n===null?'—':n.toLocaleString('en-US');
export const number=(n:number)=>String(n).padStart(3,'0');
export const clock=(ms:number)=>{const t=Math.max(0,Math.floor(ms/1000));return [Math.floor(t/3600),Math.floor(t/60)%60,t%60].map(n=>String(n).padStart(2,'0')).join(':')};
export const duration=(ms:number)=>{const m=Math.floor(ms/60000);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m} minutes`};
export async function api<T=unknown>(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await r.json();if(!r.ok){const message=data&&typeof data==='object'&&'error' in data&&typeof data.error==='string'?data.error:'Connection interrupted. Please try again.';throw new Error(message)}return data as T}
export function Header({cemetery=false,error=false}:{cemetery?:boolean;error?:boolean}){return <header className="topbar"><Link href="/" className="brand" aria-label="RE:TRY home">RE<span>:</span>TRY</Link><nav aria-label="Main navigation"><Link className={!cemetery?'selected':''} href="/">Current attempt</Link><a className={cemetery?'selected':''} href="/cemetery">Cemetery</a></nav><span className="system mono">{!error&&<span className="dot"/>}{error?'MONITOR OFFLINE':'RE:TRY MONITOR'}</span></header>}
export function Footer(){return <footer><span className="footer-brand">RE<span>:</span>TRY</span><span>EVERY FAILURE BECOMES HISTORY.</span><span>WE NEVER STOP.</span><a href="/admin">ADMIN</a></footer>}
export function Metric({label,value}:{label:string;value:string}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div>}
export function AttemptDetails({attempt,onClose}:{attempt:Attempt|null;onClose:()=>void}){return <Dialog open={!!attempt} onOpenChange={open=>!open&&onClose()}><DialogContent className="dialog-content"><DialogTitle>ATTEMPT #{attempt&&number(attempt.attempt_number)}</DialogTitle><DialogDescription className="description">{attempt?.status==='DEAD'?'A trace of the RE:TRY experiment. Final statistics are preserved.':'The current RE:TRY attempt.'}</DialogDescription>{attempt&&<><dl className="details-grid">{[['TOKEN',`${attempt.token_name} / $${attempt.token_symbol}`],['STATUS',attempt.status],['BIRTH',new Date(attempt.created_at).toLocaleString()],['DEATH',attempt.ended_at?new Date(attempt.ended_at).toLocaleString():'Still active'],['LIFESPAN',attempt.lifespan===null?'Still active':duration(attempt.lifespan)],['PEAK OBSERVED MARKET CAP',money(attempt.peak_market_cap||null)],['FINAL MARKET CAP',attempt.final_market_cap===null?'Not closed':money(attempt.final_market_cap)],['MAX OBSERVED 24H VOLUME',money(attempt.volume)],['TRANSACTIONS / FINAL 24H',num(attempt.transactions)],['BUYS / FINAL 24H',num(attempt.buys)],['SELLS / FINAL 24H',num(attempt.sells)],['FAILURE REASON',attempt.failure_reason??'Still active.'],['MINT ADDRESS',attempt.token_address]].map(([k,v])=><div key={k} className={['MINT ADDRESS','FAILURE REASON'].includes(k)?'wide':''}><dt>{k}</dt><dd className={k==='MINT ADDRESS'?'detail-mint':''}>{v}</dd></div>)}</dl>{/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(attempt.token_address)?<a className="solscan mono" href={'https://solscan.io/token/'+encodeURIComponent(attempt.token_address)} target="_blank" rel="noopener noreferrer">VIEW ON SOLSCAN</a>:<><button disabled className="solscan mono muted-button">VIEW ON SOLSCAN</button><p className="description">Available when this attempt has a real Solana mint.</p></>}</>}</DialogContent></Dialog>}

