'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
import type {Snapshot} from '@/lib/retry/types';
import {api,number} from './retry-shared';
export default function AdminControls({state,refresh}:{state:Snapshot;refresh:()=>Promise<Snapshot|null>}){
 const [closing,setClosing]=useState(false),[registering,setRegistering]=useState(false),[reason,setReason]=useState(''),[name,setName]=useState('RE:TRY'),[symbol,setSymbol]=useState('RETRY'),[mint,setMint]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(!state.isAdmin)return null;
 const logout=async()=>{try{await api('auth/logout',{});await refresh();toast.success('Signed out.')}catch(e){toast.error((e as Error).message)}};
 const close=async()=>{if(!state.attempt)return;setBusy(true);setError('');try{await api('admin',{action:'mark-dead',attemptId:state.attempt.id,reason});await refresh();setClosing(false);setReason('');toast.success('Attempt buried. Final statistics preserved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const register=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('admin',{action:'register-next',tokenName:name,tokenSymbol:symbol,tokenAddress:mint.trim()||undefined});await refresh();setRegistering(false);setMint('');toast.success('New attempt registered. Monitoring started.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <><section className="admin-box"><div><p className="eyebrow" style={{marginBottom:5}}>ADMINISTRATOR</p><p className="description">{state.attempt?'Only you decide when this attempt ends.':'The next attempt begins with a manual registration.'}</p></div><div className="admin-controls">{state.attempt?<button className="view danger-btn" onClick={()=>{setError('');setClosing(true)}}>MARK ATTEMPT AS DEAD</button>:<button className="view" onClick={()=>{setError('');setRegistering(true)}}>REGISTER NEXT ATTEMPT</button>}<button className="admin-signout" onClick={()=>void logout()}>SIGN OUT</button></div></section>
 <AlertDialog open={closing} onOpenChange={open=>!busy&&setClosing(open)}><AlertDialogContent className="dialog-content"><AlertDialogTitle>Bury attempt #{state.attempt&&number(state.attempt.attempt_number)}?</AlertDialogTitle><AlertDialogDescription className="description">This stores the final statistics and moves the attempt to the Cemetery. No new attempt starts automatically. Its mint address remains unchanged.</AlertDialogDescription><label className="field"><span>FAILURE REASON</span><Textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={500} rows={3} placeholder="Why has this attempt ended?"/></label>{error&&<p className="notice" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel className="view" disabled={busy}>CANCEL</AlertDialogCancel><AlertDialogAction className="view danger-btn" disabled={busy||!reason.trim()} onClick={e=>{e.preventDefault();void close()}}>{busy?'STORING FINAL STATS...':'CONFIRM DEAD'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={registering} onOpenChange={open=>!busy&&setRegistering(open)}><DialogContent className="dialog-content"><DialogTitle>Register the next attempt</DialogTitle><DialogDescription className="description">Add a new token to the RE:TRY sequence. This only registers metadata and starts simulated monitoring; it does not create a token on Solana.</DialogDescription><form onSubmit={e=>void register(e)}><label className="field"><span>TOKEN NAME</span><Input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></label><label className="field"><span>TOKEN SYMBOL</span><Input value={symbol} onChange={e=>setSymbol(e.target.value)} maxLength={16} required/></label><label className="field"><span>MINT ADDRESS / OPTIONAL</span><Input value={mint} onChange={e=>setMint(e.target.value)} maxLength={44} placeholder="Leave blank for a simulated mint"/></label>{error&&<p className="notice" role="alert">{error}</p>}<button className="view" type="submit" disabled={busy}>{busy?'REGISTERING...':'REGISTER ATTEMPT'}</button></form></DialogContent></Dialog></>
}
