'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Copy,Check,RotateCcw,ShieldCheck,Wallet,Activity} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import type {Attempt,Round} from '@/lib/retry/service';
import type {TokenData} from '@/lib/retry/decision';
type State={attempt:Attempt;metrics:TokenData;round:Round;history:Attempt[];roundHistory:Round[];myVote:string|null;serverTime:number;identity:string|null;pollMs:number;roundDurationMs:number;chart:number[][]};
const money=(n:number)=>'$'+Math.round(n).toLocaleString('en-US');
const num=(n:number)=>n.toLocaleString('en-US');
const number=(n:number)=>String(n).padStart(3,'0');
const clock=(ms:number)=>{const t=Math.max(0,Math.floor(ms/1000));return [Math.floor(t/3600),Math.floor(t/60)%60,t%60].map(n=>String(n).padStart(2,'0')).join(':')};
const duration=(ms:number)=>{const m=Math.floor(ms/60000);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m`};
async function api(path:string,body?:unknown){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data:any=await r.json();if(!r.ok)throw new Error(data.error??'Connection interrupted. Please try again.');return data}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div>{sub&&<div className="metric-sub">{sub}</div>}</div>}
export default function Dashboard(){
 const [state,setState]=useState<State|null>(null),[now,setNow]=useState(Date.now()),[offset,setOffset]=useState(0),[error,setError]=useState(''),[walletOpen,setWalletOpen]=useState(false),[details,setDetails]=useState<Attempt|null>(null),[protocol,setProtocol]=useState(false),[simulateOpen,setSimulateOpen]=useState(false),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false),[flash,setFlash]=useState(false);
 const stateRef=useRef(state);stateRef.current=state;
 const refresh=useCallback(async()=>{try{const data=await api('state');setState(data);setOffset(data.serverTime-Date.now());setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void refresh();const poll=setInterval(()=>void refresh(),5000),timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(timer)}},[refresh]);
 const connect=async(mode:'demo'|'wallet')=>{setBusy(true);try{const s=await api('session');let payload:unknown={mode};if(mode==='wallet'){
  const provider=(window as any).solana;if(!provider?.connect||!provider?.signMessage)throw new Error('Open this site in a Solana wallet browser, or use a demo identity.');
  const result=await provider.connect();const wallet=result.publicKey.toString();const signed=await provider.signMessage(new TextEncoder().encode(s.challenge),'utf8');payload={mode,wallet,signature:Array.from(signed.signature as Uint8Array)};
 }await api('session',payload);await refresh();setWalletOpen(false);toast.success(mode==='demo'?'Demo identity connected':'Wallet signature verified')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const vote=useCallback(async(choice:string)=>{if(!['retry','keep'].includes(choice))throw new Error('Invalid vote choice');if(!stateRef.current?.identity){setWalletOpen(true);return {status:'identity_required'}}setBusy(true);try{await api('vote',{choice});await refresh();setFlash(true);setTimeout(()=>setFlash(false),900);toast.success('Vote recorded for this round');return {status:'recorded',choice}}catch(e){toast.error((e as Error).message);throw e}finally{setBusy(false)}},[refresh]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{
  Promise.resolve(context.registerTool({name:'get_retry_state',description:'Read the current simulated attempt and community vote.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{await refresh();return {attempt:stateRef.current?.attempt,round:stateRef.current?.round}}},{signal:lifecycle.signal})).catch(()=>{});
  Promise.resolve(context.registerTool({name:'cast_retry_vote',description:'Cast one vote in the active round using the already connected voting identity. Opens the identity dialog when connection is required.',inputSchema:{type:'object',properties:{choice:{type:'string',enum:['retry','keep']}},required:['choice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{choice:string})=>vote(input.choice)},{signal:lifecycle.signal})).catch(()=>{});
 }catch{}return()=>lifecycle.abort()},[refresh,vote]);
 const time=now+offset;
 const simulate=async()=>{setBusy(true);try{if(!state?.identity){setSimulateOpen(false);setWalletOpen(true);return}await api('simulate',{});setSimulateOpen(false);await refresh()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}};
 const copy=async()=>{try{await navigator.clipboard.writeText(state!.attempt.token_address);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{toast.error('Clipboard unavailable. Select and copy the mint text.')}};
 const total=state?(state.round.retry_votes+state.round.keep_votes):0;
 const yes=total?Math.round(state!.round.retry_votes/total*100):0,no=total?100-yes:0;
 const phase=state?.attempt.status==='FAILED'?(time-(state.attempt.ended_at??time)<3000?'ATTEMPT FAILED':'RETRYING...'):null;
 const chart=state?.chart??[];
 const points=chart.map(p=>p.join(',')).join(' ');
 return <div className="wrap"><Toaster theme="dark" position="bottom-right"/>
  <header className="topbar"><a href="#" className="brand" aria-label="RE:TRY home">RE<span>:</span>TRY</a><nav aria-label="Main navigation"><a href="#current" className="active">Current attempt</a><a href="#history">History</a><button className="icon-button" onClick={()=>setProtocol(true)}>The protocol</button></nav><div className="top-actions"><span className="badge"><span className="dot"/>SYSTEM {error?'OFFLINE':'ONLINE'}</span><button className="connect" onClick={()=>setWalletOpen(true)}>{state?.identity?(state.identity.startsWith('DEMO_')?'DEMO CONNECTED':state.identity.slice(0,4)+'…'+state.identity.slice(-4)):'CONNECT WALLET'}</button></div></header>
  <section className="intro"><div><p className="eyebrow">ONE EXPERIMENT. INFINITE ATTEMPTS.</p><h1>One attempt.<br/>One more <span>chance.</span></h1></div><div className="intro-note"><b>Retry until it works.</b><br/>The attempt changes. The mission stays.</div></section>
  {error&&<div className="notice error" role="alert">{error} {state?'Showing the last received data.':''} <button className="view" onClick={()=>void refresh()}>RECONNECT</button></div>}
  {!state?<div className="panel loading"><div>INITIALIZING RE:TRY<span aria-hidden="true">_</span><p className="description">Connecting to the attempt monitor.</p></div></div>:<>
  <div className="main-grid" id="current"><section className="panel attempt-panel" aria-label="Current attempt"><div className="panel-top"><span>CURRENT ATTEMPT</span><span className="badge">SOLANA / SIMULATED</span></div><div className="attempt-heading"><div><div className="attempt-number mono"><small>#</small>{number(state.attempt.attempt_number)}</div><div className="token-label mono">$RETRY <span style={{color:'#67785b',fontSize:12}}> / SAME MISSION</span></div></div><span className={'status mono '+(phase?'failed':'')}><span className="dot"/>{state.attempt.status}</span></div>
   <div className="mint"><span>MINT</span><span className="mint-value" title={state.attempt.token_address}>{state.attempt.token_address}</span><button onClick={()=>void copy()} className="icon-button" aria-label="Copy simulated mint address">{copied?<Check size={14}/>:<Copy size={14}/>}</button></div>
   <div className="metric-grid"><Metric label="MARKET CAP" value={money(state.metrics.marketCap)} sub="SIMULATED VALUE"/><Metric label="LIQUIDITY" value={money(state.metrics.liquidity)}/><Metric label="HOLDERS" value={num(state.metrics.holders)}/></div>
   <div className="performance"><div className="chart-header mono"><span>MARKET CAP · THIS ATTEMPT</span><span>1M INTERVAL</span></div><svg className="chart" viewBox="0 0 600 120" preserveAspectRatio="none" role="img" aria-label="Simulated market cap during this attempt"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#c1f879" stopOpacity=".12"/><stop offset="100%" stopColor="#c1f879" stopOpacity="0"/></linearGradient></defs>{[30,65,100].map(y=><line key={y} x1="0" y1={y} x2="600" y2={y} stroke="#293321" strokeDasharray="3 5"/>)}<polygon points={`0,120 ${points} 588,120`} fill="url(#chart-fill)"/><polyline points={points} fill="none" stroke="#b3e66e" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/><circle cx="588" cy={chart[49]?.[1]} r="3" fill="#c1f879"/></svg><div className="chart-labels"><span>{duration(Math.min(state.metrics.ageMs,49*60000))} AGO</span><span>NOW</span></div></div>
   <div className="activity-grid"><Metric label="24H VOLUME" value={money(state.metrics.volume)}/><Metric label="BUYS" value={num(state.metrics.buys)}/><Metric label="SELLS" value={num(state.metrics.sells)}/><Metric label="TRANSACTIONS" value={num(state.metrics.transactions)}/></div><div className="age-line mono"><span><Activity size={12} style={{display:'inline',marginRight:7}}/>MONITORING ACTIVITY</span><span>AGE {clock(time-state.attempt.created_at)}</span></div>
  </section>
  <section id="vote" className={'panel vote-panel '+(flash?'voted':'')} aria-label="Community vote"><div className="panel-top"><span>COMMUNITY SIGNAL</span><ShieldCheck size={15}/></div><div className="vote-body"><h2>Should we retry?</h2><p className="description">A new attempt, or more time for this one?<br/>Make your signal count.</p><div className="round-clock mono"><div><p className="eyebrow">VOTING ROUND</p><span className="time">{clock(state.round.ends_at-time)}</span><span className="remaining">LEFT</span></div><span className="round-pill">#{String(state.round.round_number).padStart(2,'0')}</span></div><div className="vote-buttons"><button className="retry-btn" disabled={busy||!!state.myVote||!!phase||time>=state.round.ends_at} onClick={()=>void vote('retry').catch(()=>{})}><RotateCcw size={15}/>RETRY</button><button disabled={busy||!!state.myVote||!!phase||time>=state.round.ends_at} onClick={()=>void vote('keep').catch(()=>{})}>KEEP RUNNING</button></div><p className="vote-hint" aria-live="polite">{state.myVote?`✓ ${state.myVote==='retry'?'RETRY':'KEEP RUNNING'} vote recorded`:'One identity. One vote. Every 30 minutes.'}</p><div className="results-head mono"><span>YES — {yes}%</span><span>NO — {no}%</span></div><Progress aria-label="Retry vote percentage" value={yes} className="h-[7px] rounded-none bg-[#526444] [&_[data-slot=progress-indicator]]:bg-[#c1f879]"/><div className="vote-total mono"><span>TOTAL VOTES: {num(total)}</span><span>{total?'LIVE RESULTS':'AWAITING VOTES'}</span></div></div><div className="vote-foot mono">Your vote is a signal, not a trigger.<br/>The system considers performance, too.</div></section></div>
  <section className="decision mono" aria-label="Next attempt decision"><div className="decision-title">HOW THE NEXT<br/>ATTEMPT HAPPENS</div><div className="decision-equation"><span>COMMUNITY VOTE</span><b>+</b><span>TOKEN PERFORMANCE</span><b>+</b><span>SYSTEM CONDITIONS</span><b>=</b><span className="final">NEXT ATTEMPT DECISION</span></div></section>
  <section id="history"><div className="section-header"><h2>Attempt history<span style={{color:'#536447',marginLeft:12}} className="mono">/{String(state.history.length).padStart(2,'0')}</span></h2><p className="eyebrow">EVERY FAILURE IS PART OF THE PROCESS.</p></div><div className="panel history-scroll"><Table className="history-table"><TableHeader><TableRow><TableHead>ATTEMPT</TableHead><TableHead>STATUS</TableHead><TableHead>DURATION</TableHead><TableHead>PEAK MARKET CAP</TableHead><TableHead>PEAK HOLDERS</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{state.history.map(a=><TableRow key={a.id}><TableCell className="num">#{number(a.attempt_number)}</TableCell><TableCell><span className={a.status==='RUNNING'?'running-text':'failed-text'}>{a.status==='RUNNING'?'● RUNNING':'× FAILED'}</span></TableCell><TableCell>{a.status==='RUNNING'?'Current':duration((a.ended_at??time)-a.created_at)}</TableCell><TableCell>{money(a.peak_market_cap)}</TableCell><TableCell>{num(a.peak_holders)}</TableCell><TableCell><button className="view" onClick={()=>setDetails(a)} aria-label={`View attempt ${a.attempt_number}`}>VIEW</button></TableCell></TableRow>)}</TableBody></Table></div></section>
  <details className="rounds" id="rounds"><summary className="mono">VOTING ROUND ARCHIVE · {state.roundHistory.length} CLOSED ROUNDS</summary><div className="panel">{state.roundHistory.length?state.roundHistory.map(r=><div className="round-row mono" key={r.id}><span>ATTEMPT #{number(r.attempt_id)} / ROUND #{String(r.round_number).padStart(2,'0')}</span><span>YES {r.retry_votes} · NO {r.keep_votes}</span><span>{new Date(r.ends_at).toLocaleString()} · CLOSED</span></div>):<p className="empty">The first result will appear when a round closes.</p>}</div></details>
  </>}
  <footer><span className="footer-brand">RE<span>:</span>TRY <span style={{color:'#536447',marginLeft:12}}>PERSISTENCE IS THE PROTOCOL.</span></span><span>MVP / SIMULATED DATA / NO TRANSACTIONS</span><button className="simulation" onClick={()=>setSimulateOpen(true)}>TEST RETRY CYCLE</button></footer>
  <Dialog open={walletOpen} onOpenChange={setWalletOpen}><DialogContent className="dialog-content"><DialogTitle>{state?.identity?'Voting identity connected':'Connect your signal'}</DialogTitle><DialogDescription className="description">{state?.identity?'Your identity can cast one vote per round.':'Use a demo identity or verify ownership of a Solana wallet with a message signature. No transactions are requested.'}</DialogDescription>{state?.identity?<p className="mono" style={{wordBreak:'break-all',fontSize:14}}>{state.identity}<br/><span className="description">{state.identity.startsWith('DEMO_')?'Demo identity is assigned by the server. It does not prove ownership of a real wallet.':'Wallet ownership verified by signature.'}</span></p>:<><button className="option mono" disabled={busy} onClick={()=>void connect('demo')}>CONTINUE WITH DEMO IDENTITY</button><button className="option mono" disabled={busy} onClick={()=>void connect('wallet')}><Wallet size={16} style={{display:'inline',marginRight:8}}/>VERIFY SOLANA WALLET</button><p className="description">Demo votes are for testing. Real wallet voting enforces one verified wallet per round.</p></>}</DialogContent></Dialog>
  <Dialog open={!!details} onOpenChange={open=>!open&&setDetails(null)}><DialogContent className="dialog-content"><DialogTitle>ATTEMPT #{details&&number(details.attempt_number)}</DialogTitle><DialogDescription className="description">One attempt in the continuing RE:TRY experiment.</DialogDescription>{details&&<dl className="details-grid">{[['STATUS',details.status],['DURATION',duration((details.ended_at??time)-details.created_at)],['STARTED',new Date(details.created_at).toLocaleString()],['ENDED',details.ended_at?new Date(details.ended_at).toLocaleString():'Still running'],['PEAK MARKET CAP',money(details.peak_market_cap)],['PEAK HOLDERS',num(details.peak_holders)],['VOLUME',money(details.volume)],['REASON',details.failure_reason??'Monitoring continues.'],['SIMULATED MINT',details.token_address]].map(([k,v])=><div key={k} className={k==='SIMULATED MINT'?'wide':''}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}</DialogContent></Dialog>
  <Dialog open={protocol} onOpenChange={setProtocol}><DialogContent className="dialog-content"><DialogTitle>Persistence is the protocol.</DialogTitle><DialogDescription className="description">RE:TRY is one experiment with infinite attempts.</DialogDescription><p>Every attempt has its own token identity. Community votes close every 30 minutes and are kept in the archive.</p><p>A retry needs weak token performance and valid system conditions. A community majority alone cannot end an attempt.</p><p className="description">This MVP uses a simulated activity curve that gradually declines after 90 minutes. The backend evaluates configurable conditions when monitoring requests arrive. No tokens or transactions are created. The test control lets you preview a failure immediately.</p></DialogContent></Dialog>
  <AlertDialog open={simulateOpen} onOpenChange={setSimulateOpen}><AlertDialogContent className="dialog-content"><AlertDialogTitle>Test the retry cycle?</AlertDialogTitle><AlertDialogDescription className="description">This ends the current simulated attempt for everyone viewing this MVP, closes its voting round and starts the next attempt after the transition. The result remains in the history. No blockchain action takes place.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel className="view">CANCEL</AlertDialogCancel><AlertDialogAction className="connect" disabled={busy||!state||!!phase} onClick={()=>void simulate()}>SIMULATE FAILURE</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  {phase&&<div className="phase" role="status"><p className="eyebrow">RE:TRY / ATTEMPT #{number(state!.attempt.attempt_number)}</p><strong>{phase}</strong><p>Same experiment. One more chance.</p></div>}
 </div>
}

